"""Per-provider image-generation parameter whitelists."""

from __future__ import annotations

FALLBACK_TEXT_TO_IMAGE_KEYS: set[str] = {
    "prompt",
    "model",
    "prefer_provider",
    "n",
    "size",
    "aspect_ratio",
    "style",
}

FALLBACK_IMAGE_TO_IMAGE_KEYS: set[str] = {
    "image_url",
    "prompt",
    "model",
    "prefer_provider",
    "count",
    "size",
    "extra_images",
}

TEXT_TO_IMAGE_KEYS_BY_PROVIDER: dict[str, set[str]] = {
    "openai": {
        "prompt",
        "model",
        "prefer_provider",
        "n",
        "size",
        "style",
        "reference_images",
        "extra_images",
    },
    "jimeng": {
        "prompt",
        "model",
        "prefer_provider",
        "width",
        "height",
        "steps",
        "cfg_scale",
        "seed",
        "negative_prompt",
        "style",
    },
    "keling": {
        "prompt",
        "model",
        "prefer_provider",
        "n",
        "size",
        "aspect_ratio",
        "style",
        "style_preset_id",
        "style_spec",
        "negative_prompt",
        "image",
        "image_reference",
        "image_fidelity",
        "human_fidelity",
    },
    "volcengine": {
        "prompt",
        "model",
        "prefer_provider",
        "n",
        "size",
        "style",
        "style_preset_id",
        "style_spec",
        "cfg_scale",
        "watermark",
        "reference_images",
    },
    "google": {
        "prompt",
        "model",
        "prefer_provider",
        "aspect_ratio",
        "size",
        "reference_images",
        "extra_images",
        "base64_images",
        "response_modalities",
        "responseModalities",
        "image_size",
        "imageSize",
        "aspectRatio",
    },
    "codex": {
        "prompt",
        "model",
        "prefer_provider",
        "size",
        "aspect_ratio",
        "width",
        "height",
        "reference_images",
        "extra_images",
    },
}

IMAGE_TO_IMAGE_KEYS_BY_PROVIDER: dict[str, set[str]] = {
    "openai": {
        "image_url",
        "prompt",
        "model",
        "prefer_provider",
        "count",
        "size",
        "extra_images",
        "reference_images",
    },
    "jimeng": {
        "image_url",
        "prompt",
        "model",
        "prefer_provider",
        "size",
        "strength",
        "steps",
        "cfg_scale",
        "seed",
    },
    "keling": {
        "image_url",
        "prompt",
        "model",
        "prefer_provider",
        "count",
        "size",
        "aspect_ratio",
        "style",
        "style_preset_id",
        "style_spec",
        "image_reference",
        "image_fidelity",
        "human_fidelity",
    },
    "volcengine": {
        "image_url",
        "prompt",
        "model",
        "prefer_provider",
        "count",
        "size",
        "style",
        "style_preset_id",
        "style_spec",
        "extra_images",
        "cfg_scale",
        "watermark",
    },
    "google": {
        "image_url",
        "prompt",
        "model",
        "prefer_provider",
        "aspect_ratio",
        "size",
        "reference_images",
        "extra_images",
        "base64_images",
        "response_modalities",
        "responseModalities",
        "image_size",
        "imageSize",
        "aspectRatio",
    },
}
