"""
MiniMax system voice catalog

Provides a static fallback for system voices with language and bilingual names.
"""

SYSTEM_VOICE_CATALOG = [
    {"voice_id": "male-qn-qingse", "voice_name": "青涩青年音色", "language": "zh-CN"},
    {"voice_id": "male-qn-jingying", "voice_name": "精英青年音色", "language": "zh-CN"},
    {"voice_id": "male-qn-badao", "voice_name": "霸道青年音色", "language": "zh-CN"},
    {
        "voice_id": "male-qn-daxuesheng",
        "voice_name": "青年大学生音色",
        "language": "zh-CN",
    },
    {"voice_id": "female-shaonv", "voice_name": "少女音色", "language": "zh-CN"},
    {"voice_id": "female-yujie", "voice_name": "御姐音色", "language": "zh-CN"},
    {"voice_id": "female-chengshu", "voice_name": "成熟女性音色", "language": "zh-CN"},
    {"voice_id": "female-tianmei", "voice_name": "甜美女性音色", "language": "zh-CN"},
    {
        "voice_id": "male-qn-qingse-jingpin",
        "voice_name": "青涩青年音色-beta",
        "language": "zh-CN",
    },
    {
        "voice_id": "male-qn-jingying-jingpin",
        "voice_name": "精英青年音色-beta",
        "language": "zh-CN",
    },
    {
        "voice_id": "male-qn-badao-jingpin",
        "voice_name": "霸道青年音色-beta",
        "language": "zh-CN",
    },
    {
        "voice_id": "male-qn-daxuesheng-jingpin",
        "voice_name": "青年大学生音色-beta",
        "language": "zh-CN",
    },
    {
        "voice_id": "female-shaonv-jingpin",
        "voice_name": "少女音色-beta",
        "language": "zh-CN",
    },
    {
        "voice_id": "female-yujie-jingpin",
        "voice_name": "御姐音色-beta",
        "language": "zh-CN",
    },
    {
        "voice_id": "female-chengshu-jingpin",
        "voice_name": "成熟女性音色-beta",
        "language": "zh-CN",
    },
    {
        "voice_id": "female-tianmei-jingpin",
        "voice_name": "甜美女性音色-beta",
        "language": "zh-CN",
    },
    {"voice_id": "clever_boy", "voice_name": "聪明男童", "language": "zh-CN"},
    {"voice_id": "cute_boy", "voice_name": "可爱男童", "language": "zh-CN"},
    {"voice_id": "lovely_girl", "voice_name": "萌萌女童", "language": "zh-CN"},
    {"voice_id": "cartoon_pig", "voice_name": "卡通猪小琪", "language": "zh-CN"},
    {"voice_id": "bingjiao_didi", "voice_name": "病娇弟弟", "language": "zh-CN"},
    {"voice_id": "junlang_nanyou", "voice_name": "俊朗男友", "language": "zh-CN"},
    {"voice_id": "chunzhen_xuedi", "voice_name": "纯真学弟", "language": "zh-CN"},
    {"voice_id": "lengdan_xiongzhang", "voice_name": "冷淡学长", "language": "zh-CN"},
    {"voice_id": "badao_shaoye", "voice_name": "霸道少爷", "language": "zh-CN"},
    {"voice_id": "tianxin_xiaoling", "voice_name": "甜心小玲", "language": "zh-CN"},
    {"voice_id": "qiaopi_mengmei", "voice_name": "俏皮萌妹", "language": "zh-CN"},
    {"voice_id": "wumei_yujie", "voice_name": "妩媚御姐", "language": "zh-CN"},
    {"voice_id": "diadia_xuemei", "voice_name": "嗲嗲学妹", "language": "zh-CN"},
    {"voice_id": "danya_xuejie", "voice_name": "淡雅学姐", "language": "zh-CN"},
    {
        "voice_id": "Chinese (Mandarin)_Reliable_Executive",
        "voice_name": "沉稳高管",
        "language": "zh-CN",
    },
    {
        "voice_id": "Chinese (Mandarin)_News_Anchor",
        "voice_name": "新闻女声",
        "language": "zh-CN",
    },
    {
        "voice_id": "Chinese (Mandarin)_Mature_Woman",
        "voice_name": "傲娇御姐",
        "language": "zh-CN",
    },
    {
        "voice_id": "Chinese (Mandarin)_Unrestrained_Young_Man",
        "voice_name": "不羁青年",
        "language": "zh-CN",
    },
    {"voice_id": "Arrogant_Miss", "voice_name": "嚣张小姐", "language": "zh-CN"},
    {"voice_id": "Robot_Armor", "voice_name": "机械战甲", "language": "zh-CN"},
    {
        "voice_id": "Chinese (Mandarin)_Kind-hearted_Antie",
        "voice_name": "热心大婶",
        "language": "zh-CN",
    },
    {
        "voice_id": "Chinese (Mandarin)_HK_Flight_Attendant",
        "voice_name": "港普空姐",
        "language": "zh-CN",
    },
    {
        "voice_id": "Chinese (Mandarin)_Humorous_Elder",
        "voice_name": "搞笑大爷",
        "language": "zh-CN",
    },
    {
        "voice_id": "Chinese (Mandarin)_Gentleman",
        "voice_name": "温润男声",
        "language": "zh-CN",
    },
    {
        "voice_id": "Chinese (Mandarin)_Warm_Bestie",
        "voice_name": "温暖闺蜜",
        "language": "zh-CN",
    },
    {
        "voice_id": "Chinese (Mandarin)_Male_Announcer",
        "voice_name": "播报男声",
        "language": "zh-CN",
    },
    {
        "voice_id": "Chinese (Mandarin)_Sweet_Lady",
        "voice_name": "甜美女声",
        "language": "zh-CN",
    },
    {
        "voice_id": "Chinese (Mandarin)_Southern_Young_Man",
        "voice_name": "南方小哥",
        "language": "zh-CN",
    },
    {
        "voice_id": "Chinese (Mandarin)_Wise_Women",
        "voice_name": "阅历姐姐",
        "language": "zh-CN",
    },
    {
        "voice_id": "Chinese (Mandarin)_Gentle_Youth",
        "voice_name": "温润青年",
        "language": "zh-CN",
    },
    {
        "voice_id": "Chinese (Mandarin)_Warm_Girl",
        "voice_name": "温暖少女",
        "language": "zh-CN",
    },
    {
        "voice_id": "Chinese (Mandarin)_Kind-hearted_Elder",
        "voice_name": "花甲奶奶",
        "language": "zh-CN",
    },
    {
        "voice_id": "Chinese (Mandarin)_Cute_Spirit",
        "voice_name": "憨憨萌兽",
        "language": "zh-CN",
    },
    {
        "voice_id": "Chinese (Mandarin)_Radio_Host",
        "voice_name": "电台男主播",
        "language": "zh-CN",
    },
    {
        "voice_id": "Chinese (Mandarin)_Lyrical_Voice",
        "voice_name": "抒情男声",
        "language": "zh-CN",
    },
    {
        "voice_id": "Chinese (Mandarin)_Straightforward_Boy",
        "voice_name": "率真弟弟",
        "language": "zh-CN",
    },
    {
        "voice_id": "Chinese (Mandarin)_Sincere_Adult",
        "voice_name": "真诚青年",
        "language": "zh-CN",
    },
    {
        "voice_id": "Chinese (Mandarin)_Gentle_Senior",
        "voice_name": "温柔学姐",
        "language": "zh-CN",
    },
    {
        "voice_id": "Chinese (Mandarin)_Stubborn_Friend",
        "voice_name": "嘴硬竹马",
        "language": "zh-CN",
    },
    {
        "voice_id": "Chinese (Mandarin)_Crisp_Girl",
        "voice_name": "清脆少女",
        "language": "zh-CN",
    },
    {
        "voice_id": "Chinese (Mandarin)_Pure-hearted_Boy",
        "voice_name": "清澈邻家弟弟",
        "language": "zh-CN",
    },
    {
        "voice_id": "Chinese (Mandarin)_Soft_Girl",
        "voice_name": "软软女孩",
        "language": "zh-CN",
    },
    {
        "voice_id": "Cantonese_ProfessionalHost（F）",
        "voice_name": "专业女主持",
        "language": "zh-HK",
    },
    {"voice_id": "Cantonese_GentleLady", "voice_name": "温柔女声", "language": "zh-HK"},
    {
        "voice_id": "Cantonese_ProfessionalHost（M）",
        "voice_name": "专业男主持",
        "language": "zh-HK",
    },
    {"voice_id": "Cantonese_PlayfulMan", "voice_name": "活泼男声", "language": "zh-HK"},
    {"voice_id": "Cantonese_CuteGirl", "voice_name": "可爱女孩", "language": "zh-HK"},
    {"voice_id": "Cantonese_KindWoman", "voice_name": "善良女声", "language": "zh-HK"},
    {"voice_id": "Santa_Claus", "voice_name": "Santa Claus", "language": "en"},
    {"voice_id": "Grinch", "voice_name": "Grinch", "language": "en"},
    {"voice_id": "Rudolph", "voice_name": "Rudolph", "language": "en"},
    {"voice_id": "Arnold", "voice_name": "Arnold", "language": "en"},
    {"voice_id": "Charming_Santa", "voice_name": "Charming Santa", "language": "en"},
    {"voice_id": "Charming_Lady", "voice_name": "Charming Lady", "language": "en"},
    {"voice_id": "Sweet_Girl", "voice_name": "Sweet Girl", "language": "en"},
    {"voice_id": "Cute_Elf", "voice_name": "Cute Elf", "language": "en"},
    {"voice_id": "Attractive_Girl", "voice_name": "Attractive Girl", "language": "en"},
    {"voice_id": "Serene_Woman", "voice_name": "Serene Woman", "language": "en"},
    {
        "voice_id": "English_Trustworthy_Man",
        "voice_name": "Trustworthy Man",
        "language": "en",
    },
    {
        "voice_id": "English_Graceful_Lady",
        "voice_name": "Graceful Lady",
        "language": "en",
    },
    {
        "voice_id": "English_Aussie_Bloke",
        "voice_name": "Aussie Bloke",
        "language": "en",
    },
    {
        "voice_id": "English_Whispering_girl",
        "voice_name": "Whispering girl",
        "language": "en",
    },
    {
        "voice_id": "English_Diligent_Man",
        "voice_name": "Diligent Man",
        "language": "en",
    },
    {
        "voice_id": "English_Gentle-voiced_man",
        "voice_name": "Gentle-voiced man",
        "language": "en",
    },
    {
        "voice_id": "Japanese_IntellectualSenior",
        "voice_name": "Intellectual Senior",
        "language": "ja",
    },
    {
        "voice_id": "Japanese_DecisivePrincess",
        "voice_name": "Decisive Princess",
        "language": "ja",
    },
    {
        "voice_id": "Japanese_LoyalKnight",
        "voice_name": "Loyal Knight",
        "language": "ja",
    },
    {
        "voice_id": "Japanese_DominantMan",
        "voice_name": "Dominant Man",
        "language": "ja",
    },
    {
        "voice_id": "Japanese_SeriousCommander",
        "voice_name": "Serious Commander",
        "language": "ja",
    },
    {"voice_id": "Japanese_ColdQueen", "voice_name": "Cold Queen", "language": "ja"},
    {
        "voice_id": "Japanese_DependableWoman",
        "voice_name": "Dependable Woman",
        "language": "ja",
    },
    {
        "voice_id": "Japanese_GentleButler",
        "voice_name": "Gentle Butler",
        "language": "ja",
    },
    {"voice_id": "Japanese_KindLady", "voice_name": "Kind Lady", "language": "ja"},
    {"voice_id": "Japanese_CalmLady", "voice_name": "Calm Lady", "language": "ja"},
    {
        "voice_id": "Japanese_OptimisticYouth",
        "voice_name": "Optimistic Youth",
        "language": "ja",
    },
    {
        "voice_id": "Japanese_GenerousIzakayaOwner",
        "voice_name": "Generous Izakaya Owner",
        "language": "ja",
    },
    {
        "voice_id": "Japanese_SportyStudent",
        "voice_name": "Sporty Student",
        "language": "ja",
    },
    {
        "voice_id": "Japanese_InnocentBoy",
        "voice_name": "Innocent Boy",
        "language": "ja",
    },
    {
        "voice_id": "Japanese_GracefulMaiden",
        "voice_name": "Graceful Maiden",
        "language": "ja",
    },
    {"voice_id": "Korean_SweetGirl", "voice_name": "Sweet Girl", "language": "ko"},
    {
        "voice_id": "Korean_CheerfulBoyfriend",
        "voice_name": "Cheerful Boyfriend",
        "language": "ko",
    },
    {
        "voice_id": "Korean_EnchantingSister",
        "voice_name": "Enchanting Sister",
        "language": "ko",
    },
    {"voice_id": "Korean_ShyGirl", "voice_name": "Shy Girl", "language": "ko"},
    {
        "voice_id": "Korean_ReliableSister",
        "voice_name": "Reliable Sister",
        "language": "ko",
    },
    {"voice_id": "Korean_StrictBoss", "voice_name": "Strict Boss", "language": "ko"},
    {"voice_id": "Korean_SassyGirl", "voice_name": "Sassy Girl", "language": "ko"},
    {
        "voice_id": "Korean_ChildhoodFriendGirl",
        "voice_name": "Childhood Friend Girl",
        "language": "ko",
    },
    {
        "voice_id": "Korean_PlayboyCharmer",
        "voice_name": "Playboy Charmer",
        "language": "ko",
    },
    {
        "voice_id": "Korean_ElegantPrincess",
        "voice_name": "Elegant Princess",
        "language": "ko",
    },
    {
        "voice_id": "Korean_BraveFemaleWarrior",
        "voice_name": "Brave Female Warrior",
        "language": "ko",
    },
    {"voice_id": "Korean_BraveYouth", "voice_name": "Brave Youth", "language": "ko"},
    {"voice_id": "Korean_CalmLady", "voice_name": "Calm Lady", "language": "ko"},
    {
        "voice_id": "Korean_EnthusiasticTeen",
        "voice_name": "Enthusiastic Teen",
        "language": "ko",
    },
    {
        "voice_id": "Korean_SoothingLady",
        "voice_name": "Soothing Lady",
        "language": "ko",
    },
    {
        "voice_id": "Korean_IntellectualSenior",
        "voice_name": "Intellectual Senior",
        "language": "ko",
    },
    {
        "voice_id": "Korean_LonelyWarrior",
        "voice_name": "Lonely Warrior",
        "language": "ko",
    },
    {"voice_id": "Korean_MatureLady", "voice_name": "Mature Lady", "language": "ko"},
    {"voice_id": "Korean_InnocentBoy", "voice_name": "Innocent Boy", "language": "ko"},
    {
        "voice_id": "Korean_CharmingSister",
        "voice_name": "Charming Sister",
        "language": "ko",
    },
    {
        "voice_id": "Korean_AthleticStudent",
        "voice_name": "Athletic Student",
        "language": "ko",
    },
    {
        "voice_id": "Korean_BraveAdventurer",
        "voice_name": "Brave Adventurer",
        "language": "ko",
    },
    {
        "voice_id": "Korean_CalmGentleman",
        "voice_name": "Calm Gentleman",
        "language": "ko",
    },
    {"voice_id": "Korean_WiseElf", "voice_name": "Wise Elf", "language": "ko"},
    {
        "voice_id": "Korean_CheerfulCoolJunior",
        "voice_name": "Cheerful Cool Junior",
        "language": "ko",
    },
    {
        "voice_id": "Korean_DecisiveQueen",
        "voice_name": "Decisive Queen",
        "language": "ko",
    },
    {
        "voice_id": "Korean_ColdYoungMan",
        "voice_name": "Cold Young Man",
        "language": "ko",
    },
    {
        "voice_id": "Korean_MysteriousGirl",
        "voice_name": "Mysterious Girl",
        "language": "ko",
    },
    {"voice_id": "Korean_QuirkyGirl", "voice_name": "Quirky Girl", "language": "ko"},
    {
        "voice_id": "Korean_ConsiderateSenior",
        "voice_name": "Considerate Senior",
        "language": "ko",
    },
    {
        "voice_id": "Korean_CheerfulLittleSister",
        "voice_name": "Cheerful Little Sister",
        "language": "ko",
    },
    {"voice_id": "Korean_DominantMan", "voice_name": "Dominant Man", "language": "ko"},
    {
        "voice_id": "Korean_AirheadedGirl",
        "voice_name": "Airheaded Girl",
        "language": "ko",
    },
    {
        "voice_id": "Korean_ReliableYouth",
        "voice_name": "Reliable Youth",
        "language": "ko",
    },
    {
        "voice_id": "Korean_FriendlyBigSister",
        "voice_name": "Friendly Big Sister",
        "language": "ko",
    },
    {"voice_id": "Korean_GentleBoss", "voice_name": "Gentle Boss", "language": "ko"},
    {"voice_id": "Korean_ColdGirl", "voice_name": "Cold Girl", "language": "ko"},
    {"voice_id": "Korean_HaughtyLady", "voice_name": "Haughty Lady", "language": "ko"},
    {
        "voice_id": "Korean_CharmingElderSister",
        "voice_name": "Charming Elder Sister",
        "language": "ko",
    },
    {
        "voice_id": "Korean_IntellectualMan",
        "voice_name": "Intellectual Man",
        "language": "ko",
    },
    {"voice_id": "Korean_CaringWoman", "voice_name": "Caring Woman", "language": "ko"},
    {"voice_id": "Korean_WiseTeacher", "voice_name": "Wise Teacher", "language": "ko"},
    {
        "voice_id": "Korean_ConfidentBoss",
        "voice_name": "Confident Boss",
        "language": "ko",
    },
    {
        "voice_id": "Korean_AthleticGirl",
        "voice_name": "Athletic Girl",
        "language": "ko",
    },
    {
        "voice_id": "Korean_PossessiveMan",
        "voice_name": "Possessive Man",
        "language": "ko",
    },
    {"voice_id": "Korean_GentleWoman", "voice_name": "Gentle Woman", "language": "ko"},
    {"voice_id": "Korean_CockyGuy", "voice_name": "Cocky Guy", "language": "ko"},
    {
        "voice_id": "Korean_ThoughtfulWoman",
        "voice_name": "Thoughtful Woman",
        "language": "ko",
    },
    {
        "voice_id": "Korean_OptimisticYouth",
        "voice_name": "Optimistic Youth",
        "language": "ko",
    },
    {"voice_id": "Spanish_SereneWoman", "voice_name": "Serene Woman", "language": "es"},
    {
        "voice_id": "Spanish_MaturePartner",
        "voice_name": "Mature Partner",
        "language": "es",
    },
    {
        "voice_id": "Spanish_CaptivatingStoryteller",
        "voice_name": "Captivating Storyteller",
        "language": "es",
    },
    {"voice_id": "Spanish_Narrator", "voice_name": "Narrator", "language": "es"},
    {"voice_id": "Spanish_WiseScholar", "voice_name": "Wise Scholar", "language": "es"},
    {
        "voice_id": "Spanish_Kind-heartedGirl",
        "voice_name": "Kind-hearted Girl",
        "language": "es",
    },
    {
        "voice_id": "Spanish_DeterminedManager",
        "voice_name": "Determined Manager",
        "language": "es",
    },
    {"voice_id": "Spanish_BossyLeader", "voice_name": "Bossy Leader", "language": "es"},
    {
        "voice_id": "Spanish_ReservedYoungMan",
        "voice_name": "Reserved Young Man",
        "language": "es",
    },
    {
        "voice_id": "Spanish_ConfidentWoman",
        "voice_name": "Confident Woman",
        "language": "es",
    },
    {
        "voice_id": "Spanish_ThoughtfulMan",
        "voice_name": "Thoughtful Man",
        "language": "es",
    },
    {
        "voice_id": "Spanish_Strong-WilledBoy",
        "voice_name": "Strong-willed Boy",
        "language": "es",
    },
    {
        "voice_id": "Spanish_SophisticatedLady",
        "voice_name": "Sophisticated Lady",
        "language": "es",
    },
    {"voice_id": "Spanish_RationalMan", "voice_name": "Rational Man", "language": "es"},
    {
        "voice_id": "Spanish_AnimeCharacter",
        "voice_name": "Anime Character",
        "language": "es",
    },
    {
        "voice_id": "Spanish_Deep-tonedMan",
        "voice_name": "Deep-toned Man",
        "language": "es",
    },
    {
        "voice_id": "Spanish_Fussyhostess",
        "voice_name": "Fussy hostess",
        "language": "es",
    },
    {"voice_id": "Spanish_SincereTeen", "voice_name": "Sincere Teen", "language": "es"},
    {"voice_id": "Spanish_FrankLady", "voice_name": "Frank Lady", "language": "es"},
    {"voice_id": "Spanish_Comedian", "voice_name": "Comedian", "language": "es"},
    {"voice_id": "Spanish_Debator", "voice_name": "Debator", "language": "es"},
    {"voice_id": "Spanish_ToughBoss", "voice_name": "Tough Boss", "language": "es"},
    {"voice_id": "Spanish_Wiselady", "voice_name": "Wise Lady", "language": "es"},
    {
        "voice_id": "Spanish_Steadymentor",
        "voice_name": "Steady Mentor",
        "language": "es",
    },
    {"voice_id": "Spanish_Jovialman", "voice_name": "Jovial Man", "language": "es"},
    {"voice_id": "Spanish_SantaClaus", "voice_name": "Santa Claus", "language": "es"},
    {"voice_id": "Spanish_Rudolph", "voice_name": "Rudolph", "language": "es"},
    {
        "voice_id": "Spanish_Intonategirl",
        "voice_name": "Intonate Girl",
        "language": "es",
    },
    {"voice_id": "Spanish_Arnold", "voice_name": "Arnold", "language": "es"},
    {"voice_id": "Spanish_Ghost", "voice_name": "Ghost", "language": "es"},
    {
        "voice_id": "Spanish_HumorousElder",
        "voice_name": "Humorous Elder",
        "language": "es",
    },
    {
        "voice_id": "Spanish_EnergeticBoy",
        "voice_name": "Energetic Boy",
        "language": "es",
    },
    {
        "voice_id": "Spanish_WhimsicalGirl",
        "voice_name": "Whimsical Girl",
        "language": "es",
    },
    {"voice_id": "Spanish_StrictBoss", "voice_name": "Strict Boss", "language": "es"},
    {"voice_id": "Spanish_ReliableMan", "voice_name": "Reliable Man", "language": "es"},
    {"voice_id": "Spanish_SereneElder", "voice_name": "Serene Elder", "language": "es"},
    {"voice_id": "Spanish_AngryMan", "voice_name": "Angry Man", "language": "es"},
    {
        "voice_id": "Spanish_AssertiveQueen",
        "voice_name": "Assertive Queen",
        "language": "es",
    },
    {
        "voice_id": "Spanish_CaringGirlfriend",
        "voice_name": "Caring Girlfriend",
        "language": "es",
    },
    {
        "voice_id": "Spanish_PowerfulSoldier",
        "voice_name": "Powerful Soldier",
        "language": "es",
    },
    {
        "voice_id": "Spanish_PassionateWarrior",
        "voice_name": "Passionate Warrior",
        "language": "es",
    },
    {"voice_id": "Spanish_ChattyGirl", "voice_name": "Chatty Girl", "language": "es"},
    {
        "voice_id": "Spanish_RomanticHusband",
        "voice_name": "Romantic Husband",
        "language": "es",
    },
    {
        "voice_id": "Spanish_CompellingGirl",
        "voice_name": "Compelling Girl",
        "language": "es",
    },
    {
        "voice_id": "Spanish_PowerfulVeteran",
        "voice_name": "Powerful Veteran",
        "language": "es",
    },
    {
        "voice_id": "Spanish_SensibleManager",
        "voice_name": "Sensible Manager",
        "language": "es",
    },
    {
        "voice_id": "Spanish_ThoughtfulLady",
        "voice_name": "Thoughtful Lady",
        "language": "es",
    },
    {
        "voice_id": "Portuguese_SentimentalLady",
        "voice_name": "Sentimental Lady",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_BossyLeader",
        "voice_name": "Bossy Leader",
        "language": "pt",
    },
    {"voice_id": "Portuguese_Wiselady", "voice_name": "Wise lady", "language": "pt"},
    {
        "voice_id": "Portuguese_Strong-WilledBoy",
        "voice_name": "Strong-willed Boy",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_Deep-VoicedGentleman",
        "voice_name": "Deep-voiced Gentleman",
        "language": "pt",
    },
    {"voice_id": "Portuguese_UpsetGirl", "voice_name": "Upset Girl", "language": "pt"},
    {
        "voice_id": "Portuguese_PassionateWarrior",
        "voice_name": "Passionate Warrior",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_AnimeCharacter",
        "voice_name": "Anime Character",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_ConfidentWoman",
        "voice_name": "Confident Woman",
        "language": "pt",
    },
    {"voice_id": "Portuguese_AngryMan", "voice_name": "Angry Man", "language": "pt"},
    {
        "voice_id": "Portuguese_CaptivatingStoryteller",
        "voice_name": "Captivating Storyteller",
        "language": "pt",
    },
    {"voice_id": "Portuguese_Godfather", "voice_name": "Godfather", "language": "pt"},
    {
        "voice_id": "Portuguese_ReservedYoungMan",
        "voice_name": "Reserved Young Man",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_SmartYoungGirl",
        "voice_name": "Smart Young Girl",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_Kind-heartedGirl",
        "voice_name": "Kind-hearted Girl",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_Pompouslady",
        "voice_name": "Pompous lady",
        "language": "pt",
    },
    {"voice_id": "Portuguese_Grinch", "voice_name": "Grinch", "language": "pt"},
    {"voice_id": "Portuguese_Debator", "voice_name": "Debator", "language": "pt"},
    {"voice_id": "Portuguese_SweetGirl", "voice_name": "Sweet Girl", "language": "pt"},
    {
        "voice_id": "Portuguese_AttractiveGirl",
        "voice_name": "Attractive Girl",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_ThoughtfulMan",
        "voice_name": "Thoughtful Man",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_PlayfulGirl",
        "voice_name": "Playful Girl",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_GorgeousLady",
        "voice_name": "Gorgeous Lady",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_LovelyLady",
        "voice_name": "Lovely Lady",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_SereneWoman",
        "voice_name": "Serene Woman",
        "language": "pt",
    },
    {"voice_id": "Portuguese_SadTeen", "voice_name": "Sad Teen", "language": "pt"},
    {
        "voice_id": "Portuguese_MaturePartner",
        "voice_name": "Mature Partner",
        "language": "pt",
    },
    {"voice_id": "Portuguese_Comedian", "voice_name": "Comedian", "language": "pt"},
    {
        "voice_id": "Portuguese_NaughtySchoolgirl",
        "voice_name": "Naughty Schoolgirl",
        "language": "pt",
    },
    {"voice_id": "Portuguese_Narrator", "voice_name": "Narrator", "language": "pt"},
    {"voice_id": "Portuguese_ToughBoss", "voice_name": "Tough Boss", "language": "pt"},
    {
        "voice_id": "Portuguese_Fussyhostess",
        "voice_name": "Fussy hostess",
        "language": "pt",
    },
    {"voice_id": "Portuguese_Dramatist", "voice_name": "Dramatist", "language": "pt"},
    {
        "voice_id": "Portuguese_Steadymentor",
        "voice_name": "Steady Mentor",
        "language": "pt",
    },
    {"voice_id": "Portuguese_Jovialman", "voice_name": "Jovial Man", "language": "pt"},
    {
        "voice_id": "Portuguese_CharmingQueen",
        "voice_name": "Charming Queen",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_SantaClaus",
        "voice_name": "Santa Claus",
        "language": "pt",
    },
    {"voice_id": "Portuguese_Rudolph", "voice_name": "Rudolph", "language": "pt"},
    {"voice_id": "Portuguese_Arnold", "voice_name": "Arnold", "language": "pt"},
    {
        "voice_id": "Portuguese_CharmingSanta",
        "voice_name": "Charming Santa",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_CharmingLady",
        "voice_name": "Charming Lady",
        "language": "pt",
    },
    {"voice_id": "Portuguese_Ghost", "voice_name": "Ghost", "language": "pt"},
    {
        "voice_id": "Portuguese_HumorousElder",
        "voice_name": "Humorous Elder",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_CalmLeader",
        "voice_name": "Calm Leader",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_GentleTeacher",
        "voice_name": "Gentle Teacher",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_EnergeticBoy",
        "voice_name": "Energetic Boy",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_ReliableMan",
        "voice_name": "Reliable Man",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_SereneElder",
        "voice_name": "Serene Elder",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_GrimReaper",
        "voice_name": "Grim Reaper",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_AssertiveQueen",
        "voice_name": "Assertive Queen",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_WhimsicalGirl",
        "voice_name": "Whimsical Girl",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_StressedLady",
        "voice_name": "Stressed Lady",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_FriendlyNeighbor",
        "voice_name": "Friendly Neighbor",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_CaringGirlfriend",
        "voice_name": "Caring Girlfriend",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_PowerfulSoldier",
        "voice_name": "Powerful Soldier",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_FascinatingBoy",
        "voice_name": "Fascinating Boy",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_RomanticHusband",
        "voice_name": "Romantic Husband",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_StrictBoss",
        "voice_name": "Strict Boss",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_InspiringLady",
        "voice_name": "Inspiring Lady",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_PlayfulSpirit",
        "voice_name": "Playful Spirit",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_ElegantGirl",
        "voice_name": "Elegant Girl",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_CompellingGirl",
        "voice_name": "Compelling Girl",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_PowerfulVeteran",
        "voice_name": "Powerful Veteran",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_SensibleManager",
        "voice_name": "Sensible Manager",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_ThoughtfulLady",
        "voice_name": "Thoughtful Lady",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_TheatricalActor",
        "voice_name": "Theatrical Actor",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_FragileBoy",
        "voice_name": "Fragile Boy",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_ChattyGirl",
        "voice_name": "Chatty Girl",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_Conscientiousinstructor",
        "voice_name": "Conscientious Instructor",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_RationalMan",
        "voice_name": "Rational Man",
        "language": "pt",
    },
    {
        "voice_id": "Portuguese_WiseScholar",
        "voice_name": "Wise Scholar",
        "language": "pt",
    },
    {"voice_id": "Portuguese_FrankLady", "voice_name": "Frank Lady", "language": "pt"},
    {
        "voice_id": "Portuguese_DeterminedManager",
        "voice_name": "Determined Manager",
        "language": "pt",
    },
    {
        "voice_id": "French_Male_Speech_New",
        "voice_name": "Level-Headed Man",
        "language": "fr",
    },
    {
        "voice_id": "French_Female_News Anchor",
        "voice_name": "Patient Female Presenter",
        "language": "fr",
    },
    {"voice_id": "French_CasualMan", "voice_name": "Casual Man", "language": "fr"},
    {
        "voice_id": "French_MovieLeadFemale",
        "voice_name": "Movie Lead Female",
        "language": "fr",
    },
    {
        "voice_id": "French_FemaleAnchor",
        "voice_name": "Female Anchor",
        "language": "fr",
    },
    {
        "voice_id": "French_MaleNarrator",
        "voice_name": "Male Narrator",
        "language": "fr",
    },
    {"voice_id": "Indonesian_SweetGirl", "voice_name": "Sweet Girl", "language": "id"},
    {
        "voice_id": "Indonesian_ReservedYoungMan",
        "voice_name": "Reserved Young Man",
        "language": "id",
    },
    {
        "voice_id": "Indonesian_CharmingGirl",
        "voice_name": "Charming Girl",
        "language": "id",
    },
    {"voice_id": "Indonesian_CalmWoman", "voice_name": "Calm Woman", "language": "id"},
    {
        "voice_id": "Indonesian_ConfidentWoman",
        "voice_name": "Confident Woman",
        "language": "id",
    },
    {"voice_id": "Indonesian_CaringMan", "voice_name": "Caring Man", "language": "id"},
    {
        "voice_id": "Indonesian_BossyLeader",
        "voice_name": "Bossy Leader",
        "language": "id",
    },
    {
        "voice_id": "Indonesian_DeterminedBoy",
        "voice_name": "Determined Boy",
        "language": "id",
    },
    {
        "voice_id": "Indonesian_GentleGirl",
        "voice_name": "Gentle Girl",
        "language": "id",
    },
    {"voice_id": "German_FriendlyMan", "voice_name": "Friendly Man", "language": "de"},
    {"voice_id": "German_SweetLady", "voice_name": "Sweet Lady", "language": "de"},
    {"voice_id": "German_PlayfulMan", "voice_name": "Playful Man", "language": "de"},
    {
        "voice_id": "Russian_HandsomeChildhoodFriend",
        "voice_name": "Handsome Childhood Friend",
        "language": "ru",
    },
    {
        "voice_id": "Russian_BrightHeroine",
        "voice_name": "Bright Queen",
        "language": "ru",
    },
    {
        "voice_id": "Russian_AmbitiousWoman",
        "voice_name": "Ambitious Woman",
        "language": "ru",
    },
    {"voice_id": "Russian_ReliableMan", "voice_name": "Reliable Man", "language": "ru"},
    {"voice_id": "Russian_CrazyQueen", "voice_name": "Crazy Girl", "language": "ru"},
    {
        "voice_id": "Russian_PessimisticGirl",
        "voice_name": "Pessimistic Girl",
        "language": "ru",
    },
    {
        "voice_id": "Russian_AttractiveGuy",
        "voice_name": "Attractive Guy",
        "language": "ru",
    },
    {
        "voice_id": "Russian_Bad-temperedBoy",
        "voice_name": "Bad-tempered Boy",
        "language": "ru",
    },
    {
        "voice_id": "Italian_BraveHeroine",
        "voice_name": "Brave Heroine",
        "language": "it",
    },
    {"voice_id": "Italian_Narrator", "voice_name": "Narrator", "language": "it"},
    {
        "voice_id": "Italian_WanderingSorcerer",
        "voice_name": "Wandering Sorcerer",
        "language": "it",
    },
    {
        "voice_id": "Italian_DiligentLeader",
        "voice_name": "Diligent Leader",
        "language": "it",
    },
    {"voice_id": "Arabic_CalmWoman", "voice_name": "Calm Woman", "language": "ar"},
    {"voice_id": "Arabic_FriendlyGuy", "voice_name": "Friendly Guy", "language": "ar"},
    {"voice_id": "Turkish_CalmWoman", "voice_name": "Calm Woman", "language": "tr"},
    {
        "voice_id": "Turkish_Trustworthyman",
        "voice_name": "Trustworthy man",
        "language": "tr",
    },
    {"voice_id": "Ukrainian_CalmWoman", "voice_name": "Calm Woman", "language": "uk"},
    {
        "voice_id": "Ukrainian_WiseScholar",
        "voice_name": "Wise Scholar",
        "language": "uk",
    },
    {
        "voice_id": "Dutch_kindhearted_girl",
        "voice_name": "Kind-hearted girl",
        "language": "nl",
    },
    {"voice_id": "Dutch_bossy_leader", "voice_name": "Bossy leader", "language": "nl"},
    {
        "voice_id": "Vietnamese_kindhearted_girl",
        "voice_name": "Kind-hearted girl",
        "language": "vi",
    },
    {"voice_id": "Thai_male_1_sample8", "voice_name": "Serene Man", "language": "th"},
    {"voice_id": "Thai_male_2_sample2", "voice_name": "Friendly Man", "language": "th"},
    {
        "voice_id": "Thai_female_1_sample1",
        "voice_name": "Confident Woman",
        "language": "th",
    },
    {
        "voice_id": "Thai_female_2_sample2",
        "voice_name": "Energetic Woman",
        "language": "th",
    },
    {
        "voice_id": "Polish_male_1_sample4",
        "voice_name": "Male Narrator",
        "language": "pl",
    },
    {
        "voice_id": "Polish_male_2_sample3",
        "voice_name": "Male Anchor",
        "language": "pl",
    },
    {
        "voice_id": "Polish_female_1_sample1",
        "voice_name": "Calm Woman",
        "language": "pl",
    },
    {
        "voice_id": "Polish_female_2_sample3",
        "voice_name": "Casual Woman",
        "language": "pl",
    },
    {
        "voice_id": "Romanian_male_1_sample2",
        "voice_name": "Reliable Man",
        "language": "ro",
    },
    {
        "voice_id": "Romanian_male_2_sample1",
        "voice_name": "Energetic Youth",
        "language": "ro",
    },
    {
        "voice_id": "Romanian_female_1_sample4",
        "voice_name": "Optimistic Youth",
        "language": "ro",
    },
    {
        "voice_id": "Romanian_female_2_sample1",
        "voice_name": "Gentle Woman",
        "language": "ro",
    },
    {
        "voice_id": "greek_male_1a_v1",
        "voice_name": "Thoughtful Mentor",
        "language": "el",
    },
    {
        "voice_id": "Greek_female_1_sample1",
        "voice_name": "Gentle Lady",
        "language": "el",
    },
    {
        "voice_id": "Greek_female_2_sample3",
        "voice_name": "Girl Next Door",
        "language": "el",
    },
    {
        "voice_id": "czech_male_1_v1",
        "voice_name": "Assured Presenter",
        "language": "cs",
    },
    {
        "voice_id": "czech_female_5_v7",
        "voice_name": "Steadfast Narrator",
        "language": "cs",
    },
    {"voice_id": "czech_female_2_v2", "voice_name": "Elegant Lady", "language": "cs"},
    {"voice_id": "finnish_male_3_v1", "voice_name": "Upbeat Man", "language": "fi"},
    {"voice_id": "finnish_male_1_v2", "voice_name": "Friendly Boy", "language": "fi"},
    {
        "voice_id": "finnish_female_4_v1",
        "voice_name": "Assetive Woman",
        "language": "fi",
    },
    {
        "voice_id": "hindi_male_1_v2",
        "voice_name": "Trustworthy Advisor",
        "language": "hi",
    },
    {"voice_id": "hindi_female_2_v1", "voice_name": "Tranquil Woman", "language": "hi"},
    {"voice_id": "hindi_female_1_v2", "voice_name": "News Anchor", "language": "hi"},
]
