---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	allocate_budget(allocate_budget)
	generate_dialogue(generate_dialogue)
	tts_trial(tts_trial)
	validate_duration(validate_duration)
	commit_scene(commit_scene)
	prepare_retry(prepare_retry)
	assemble_episode(assemble_episode)
	final_validation(final_validation)
	__end__([<p>__end__</p>]):::last
	__start__ --> allocate_budget;
	allocate_budget -. &nbsp;failed&nbsp; .-> __end__;
	allocate_budget -. &nbsp;assemble&nbsp; .-> assemble_episode;
	allocate_budget -. &nbsp;generate&nbsp; .-> generate_dialogue;
	assemble_episode --> final_validation;
	commit_scene -. &nbsp;assemble&nbsp; .-> assemble_episode;
	commit_scene -. &nbsp;continue&nbsp; .-> generate_dialogue;
	generate_dialogue -. &nbsp;failed&nbsp; .-> __end__;
	generate_dialogue -. &nbsp;tts&nbsp; .-> tts_trial;
	prepare_retry --> generate_dialogue;
	tts_trial --> validate_duration;
	validate_duration -. &nbsp;commit&nbsp; .-> commit_scene;
	validate_duration -. &nbsp;retry&nbsp; .-> prepare_retry;
	final_validation --> __end__;
	generate_dialogue -. &nbsp;retry&nbsp; .-> generate_dialogue;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
