---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	generate_step_outline(generate_step_outline)
	validate_outline(validate_outline)
	generate_episodes(generate_episodes)
	fail(fail)
	__end__([<p>__end__</p>]):::last
	__start__ --> generate_step_outline;
	generate_step_outline --> validate_outline;
	validate_outline -.-> fail;
	validate_outline -. &nbsp;ok&nbsp; .-> generate_episodes;
	fail --> __end__;
	generate_episodes --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
