---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	draft(draft)
	validate_schema(validate_schema)
	repair_output(repair_output)
	fail(fail)
	__end__([<p>__end__</p>]):::last
	__start__ --> draft;
	draft --> validate_schema;
	repair_output --> validate_schema;
	validate_schema -. &nbsp;ok&nbsp; .-> __end__;
	validate_schema -.-> fail;
	validate_schema -. &nbsp;repair&nbsp; .-> repair_output;
	fail --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
