"""Initial_migration

Revision ID: 919189f166fc
Revises: 
Create Date: 2025-07-18 22:54:05.567798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '919189f166fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('script_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='模板名称'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='模板分类'),
    sa.Column('template_content', sa.Text(), nullable=True, comment='模板内容'),
    sa.Column('structure', sa.JSON(), nullable=True, comment='结构定义'),
    sa.Column('variables', sa.JSON(), nullable=True, comment='变量定义'),
    sa.Column('usage_count', sa.Integer(), nullable=True, comment='使用次数'),
    sa.Column('rating', sa.Float(), nullable=True, comment='评分'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('is_public', sa.Boolean(), nullable=True, comment='是否公开'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_script_templates_id'), 'script_templates', ['id'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='故事标题'),
    sa.Column('genre', sa.String(length=50), nullable=False, comment='故事类型'),
    sa.Column('theme', sa.String(length=255), nullable=True, comment='故事主题'),
    sa.Column('target_audience', sa.String(length=100), nullable=True, comment='目标受众'),
    sa.Column('duration_minutes', sa.Integer(), nullable=True, comment='预计总时长（分钟）'),
    sa.Column('premise', sa.Text(), nullable=True, comment='故事前提'),
    sa.Column('synopsis', sa.Text(), nullable=True, comment='故事概要'),
    sa.Column('main_conflict', sa.Text(), nullable=True, comment='主要冲突'),
    sa.Column('resolution', sa.Text(), nullable=True, comment='解决方案'),
    sa.Column('main_characters', sa.JSON(), nullable=True, comment='主要角色列表'),
    sa.Column('character_relationships', sa.JSON(), nullable=True, comment='角色关系'),
    sa.Column('setting_time', sa.String(length=100), nullable=True, comment='时间设定'),
    sa.Column('setting_location', sa.String(length=255), nullable=True, comment='地点设定'),
    sa.Column('world_building', sa.Text(), nullable=True, comment='世界观设定'),
    sa.Column('generation_prompt', sa.Text(), nullable=True, comment='生成提示词'),
    sa.Column('ai_model', sa.String(length=50), nullable=True, comment='使用的AI模型'),
    sa.Column('generation_params', sa.JSON(), nullable=True, comment='生成参数'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态：draft, approved, published'),
    sa.Column('is_public', sa.Boolean(), nullable=True, comment='是否公开'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签列表'),
    sa.Column('extra_metadata', sa.JSON(), nullable=True, comment='额外元数据'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_id'), 'stories', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('virtual_ips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('background_story', sa.Text(), nullable=True),
    sa.Column('style_prompt', sa.Text(), nullable=True),
    sa.Column('style_reference_images', sa.JSON(), nullable=True),
    sa.Column('default_avatar_url', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_virtual_ips_id'), 'virtual_ips', ['id'], unique=False)
    op.create_index(op.f('ix_virtual_ips_name'), 'virtual_ips', ['name'], unique=True)
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False, comment='故事ID'),
    sa.Column('episode_number', sa.Integer(), nullable=False, comment='集数'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='剧集标题'),
    sa.Column('summary', sa.Text(), nullable=True, comment='剧集概要'),
    sa.Column('plot_points', sa.JSON(), nullable=True, comment='情节要点'),
    sa.Column('character_arcs', sa.JSON(), nullable=True, comment='角色发展'),
    sa.Column('conflicts', sa.JSON(), nullable=True, comment='冲突点'),
    sa.Column('duration_minutes', sa.Integer(), nullable=True, comment='预计时长（分钟）'),
    sa.Column('scene_count', sa.Integer(), nullable=True, comment='场景数量'),
    sa.Column('generation_prompt', sa.Text(), nullable=True, comment='生成提示词'),
    sa.Column('ai_model', sa.String(length=50), nullable=True, comment='使用的AI模型'),
    sa.Column('generation_params', sa.JSON(), nullable=True, comment='生成参数'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态：draft, approved, published'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签列表'),
    sa.Column('extra_metadata', sa.JSON(), nullable=True, comment='额外元数据'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episodes_id'), 'episodes', ['id'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.create_table('story_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False, comment='故事ID'),
    sa.Column('virtual_ip_id', sa.Integer(), nullable=False, comment='虚拟IP ID'),
    sa.Column('character_name', sa.String(length=100), nullable=True, comment='角色名称'),
    sa.Column('role_type', sa.String(length=50), nullable=True, comment='角色类型：protagonist, antagonist, supporting'),
    sa.Column('importance', sa.Integer(), nullable=True, comment='重要度：1-5'),
    sa.Column('personality', sa.Text(), nullable=True, comment='性格特点'),
    sa.Column('background', sa.Text(), nullable=True, comment='背景故事'),
    sa.Column('motivation', sa.Text(), nullable=True, comment='动机'),
    sa.Column('character_arc', sa.Text(), nullable=True, comment='角色发展弧线'),
    sa.Column('relationships', sa.JSON(), nullable=True, comment='与其他角色的关系'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.ForeignKeyConstraint(['virtual_ip_id'], ['virtual_ips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_characters_id'), 'story_characters', ['id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.Enum('IMAGE_GENERATION', 'IMAGE_EDIT', 'IMAGE_ENHANCEMENT', name='tasktype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='taskstatus'), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.Column('result_file_path', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_table('virtual_ip_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('virtual_ip_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=False),
    sa.Column('original_filename', sa.String(length=128), nullable=False),
    sa.Column('file_path', sa.String(length=256), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('subcategory', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('ai_model', sa.String(length=64), nullable=True),
    sa.Column('generation_params', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['virtual_ip_id'], ['virtual_ips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_virtual_ip_images_id'), 'virtual_ip_images', ['id'], unique=False)
    op.create_table('scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False, comment='剧集ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='剧本标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='剧本内容'),
    sa.Column('scenes', sa.JSON(), nullable=True, comment='场景列表'),
    sa.Column('dialogues', sa.JSON(), nullable=True, comment='对话列表'),
    sa.Column('stage_directions', sa.JSON(), nullable=True, comment='舞台指示'),
    sa.Column('format_type', sa.String(length=50), nullable=True, comment='剧本格式类型'),
    sa.Column('language', sa.String(length=10), nullable=True, comment='语言'),
    sa.Column('page_count', sa.Integer(), nullable=True, comment='页数'),
    sa.Column('word_count', sa.Integer(), nullable=True, comment='字数'),
    sa.Column('character_count', sa.Integer(), nullable=True, comment='字符数'),
    sa.Column('generation_prompt', sa.Text(), nullable=True, comment='生成提示词'),
    sa.Column('ai_model', sa.String(length=50), nullable=True, comment='使用的AI模型'),
    sa.Column('generation_params', sa.JSON(), nullable=True, comment='生成参数'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态：draft, approved, published'),
    sa.Column('version', sa.String(length=20), nullable=True, comment='版本号'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签列表'),
    sa.Column('extra_metadata', sa.JSON(), nullable=True, comment='额外元数据'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scripts_id'), 'scripts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scripts_id'), table_name='scripts')
    op.drop_table('scripts')
    op.drop_index(op.f('ix_virtual_ip_images_id'), table_name='virtual_ip_images')
    op.drop_table('virtual_ip_images')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_story_characters_id'), table_name='story_characters')
    op.drop_table('story_characters')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_episodes_id'), table_name='episodes')
    op.drop_table('episodes')
    op.drop_index(op.f('ix_virtual_ips_name'), table_name='virtual_ips')
    op.drop_index(op.f('ix_virtual_ips_id'), table_name='virtual_ips')
    op.drop_table('virtual_ips')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stories_id'), table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_script_templates_id'), table_name='script_templates')
    op.drop_table('script_templates')
    # ### end Alembic commands ###
