"""Add biography field to virtual_ips and fix string lengths

Revision ID: e5f3948ee82e
Revises: 0002_add_user_management_fields
Create Date: 2025-08-24 17:25:42.686193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e5f3948ee82e'
down_revision: Union[str, Sequence[str], None] = '0002_add_user_management_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'filename',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('images', 'original_filename',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('images', 'file_path',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.alter_column('images', 'mime_type',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('tasks', 'result_file_path',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment='账户是否激活（默认未激活）',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'is_superuser',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否为超级用户',
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=True)
    op.add_column('virtual_ips', sa.Column('biography', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('virtual_ips', 'biography')
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('users', 'is_superuser',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否为超级用户',
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='账户是否激活（默认未激活）',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('tasks', 'result_file_path',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=True)
    op.alter_column('images', 'mime_type',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('images', 'file_path',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=False)
    op.alter_column('images', 'original_filename',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('images', 'filename',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###
