"""20250824_201257_add_oss_url_to_virtual_ip_images

Revision ID: fe284ccd1b92
Revises: e5f3948ee82e
Create Date: 2025-08-24 20:12:57.220858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe284ccd1b92'
down_revision: Union[str, Sequence[str], None] = 'e5f3948ee82e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_ip_images', sa.Column('oss_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('virtual_ip_images', 'oss_url')
    # ### end Alembic commands ###
