version: "3.9"

services:
  ai-video-mysql:
    image: mysql:8.0
    container_name: ai-video-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-ai-video}
      MYSQL_DATABASE: ai_video_studio
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    volumes:
      - mysql_data:/var/lib/mysql

  ai-video-redis:
    image: redis
    container_name: ai-video-redis
    restart: always
    volumes:
      - redis_data:/data

  ai-video-backend:
    container_name: ai-video-backend
    image: "registry.cn-beijing.aliyuncs.com/geyunfei/ai-video-backend:${IMAGE_TAG:-latest}"
    env_file:
      - .env
    command: ["/bin/bash", "/app/backend-entrypoint.sh"]
    volumes:
      - uploads_data:/app/ai-pic-backend/uploads
    depends_on:
      - ai-video-mysql
      - ai-video-redis
    restart: always

  ai-video-celery-worker:
    container_name: ai-video-celery-worker
    image: "registry.cn-beijing.aliyuncs.com/geyunfei/ai-video-backend:${IMAGE_TAG:-latest}"
    env_file:
      - .env
    working_dir: /app/ai-pic-backend
    command:
      [
        "celery",
        "-A",
        "app.core.celery_app.celery_app",
        "worker",
        "-l",
        "info",
        "-c",
        "8",
      ]
    volumes:
      - uploads_data:/app/ai-pic-backend/uploads
    depends_on:
      - ai-video-backend
      - ai-video-redis
    restart: always

  ai-video-celery-beat:
    container_name: ai-video-celery-beat
    image: "registry.cn-beijing.aliyuncs.com/geyunfei/ai-video-backend:${IMAGE_TAG:-latest}"
    env_file:
      - .env
    working_dir: /app/ai-pic-backend
    command:
      ["celery", "-A", "app.core.celery_app.celery_app", "beat", "-l", "info"]
    volumes:
      - uploads_data:/app/ai-pic-backend/uploads
    depends_on:
      - ai-video-backend
      - ai-video-redis
    restart: always

  ai-video-frontend:
    container_name: ai-video-frontend
    image: "registry.cn-beijing.aliyuncs.com/geyunfei/ai-video-frontend:${IMAGE_TAG:-latest}"
    env_file:
      - .env
    working_dir: /app/ai-pic-frontend
    command:
      ["npm", "run", "start", "--", "--hostname", "0.0.0.0", "--port", "3000"]
    depends_on:
      - ai-video-backend
    restart: always

  ai-video-nginx:
    container_name: ai-video-nginx
    image: nginx
    depends_on:
      - ai-video-frontend
      - ai-video-backend
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
    restart: always

volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/mysql
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/redis
  uploads_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/uploads
