import type {
  ProductionCanvasEdge,
  ProductionCanvasNode,
  ProductionCanvasPort,
} from "./productionCanvasModel";

const port = (
  id: string,
  label: string,
  type: ProductionCanvasPort["type"],
  required = false,
): ProductionCanvasPort => ({ id, label, type, required });

const node = (
  id: string,
  label: string,
  title: string,
  detail: string,
  position: [x: number, y: number, width: number],
  inputPorts: ProductionCanvasPort[],
  outputPorts: ProductionCanvasPort[],
  status: ProductionCanvasNode["status"] = "blocked",
): ProductionCanvasNode => ({
  id,
  label,
  title,
  detail,
  status,
  x: position[0],
  y: position[1],
  width: position[2],
  definitionVersion: 1,
  inputPorts,
  outputPorts,
});

const edge = (
  from: string,
  fromPort: string,
  to: string,
  toPort: string,
  bindingType: ProductionCanvasEdge["bindingType"] = "value",
): ProductionCanvasEdge => ({
  edgeId: `${from}-${fromPort}-to-${to}-${toPort}`,
  from,
  fromPort,
  to,
  toPort,
  bindingType,
  required: true,
});

export const productionCanvasNodes: ProductionCanvasNode[] = [
  node(
    "brief",
    "Brief",
    "IP、受众、题材和单集目标",
    "把 IP、受众、题材和单集目标收敛成可执行输入。",
    [40, 128, 170],
    [],
    [port("production_brief", "生产简报", "text")],
    "ready",
  ),
  node(
    "assets",
    "Assets",
    "IP 与环境资产选择",
    "选择本次生产复用的角色与环境资产。",
    [270, 228, 190],
    [port("production_brief", "生产简报", "text", true)],
    [port("selected_assets", "选中资产", "entity_ref")],
    "review",
  ),
  node(
    "script",
    "Script",
    "短剧节拍、对白和质量门禁",
    "承接 brief，生成短剧节拍、对白、冲突和质量门禁。",
    [270, 64, 190],
    [
      port("production_brief", "生产简报", "text", true),
      port("selected_assets", "选中资产", "entity_ref"),
    ],
    [port("script", "剧本", "entity_ref")],
  ),
  node(
    "timeline",
    "Timeline",
    "镜头顺序、时长和可播放输出",
    "组装音频与 Timeline，并输出 stable clip。",
    [1000, 84, 170],
    [port("script", "剧本", "entity_ref", true)],
    [
      port("timeline", "时间线", "entity_ref"),
      port("timeline_clip", "稳定片段", "entity_ref"),
    ],
  ),
  node(
    "storyboard",
    "Storyboard Candidates",
    "镜头表、画面描述和分镜候选",
    "按片段时长生成整张故事板并人工选用。",
    [520, 228, 210],
    [port("timeline_clip", "稳定片段", "entity_ref", true)],
    [port("approved_storyboard", "选用故事板", "image")],
  ),
  node(
    "video",
    "Video Candidates",
    "图生视频、模型对比和失败重跑",
    "使用整张故事板生成视频，不使用首帧或尾帧。",
    [760, 148, 200],
    [port("approved_storyboard", "选用故事板", "image", true)],
    [port("approved_video", "选用视频", "video")],
    "running",
  ),
  node(
    "placement",
    "Timeline Place",
    "显式回填稳定片段",
    "把人工选用的视频写入 stable clip_id。",
    [760, 260, 200],
    [
      port("timeline_clip", "稳定片段", "entity_ref", true),
      port("approved_video", "选用视频", "video", true),
    ],
    [port("placed_timeline", "已回填时间线", "entity_ref")],
  ),
  node(
    "render",
    "Render",
    "渲染已回填时间线",
    "只渲染显式放置后的 Timeline 版本。",
    [520, 64, 210],
    [port("timeline", "时间线", "entity_ref", true)],
    [port("rendered_video", "渲染视频", "video")],
  ),
  node(
    "export",
    "Export",
    "导出审核成片",
    "保留最终成片与交付证据。",
    [1000, 172, 170],
    [port("rendered_video", "渲染视频", "video", true)],
    [
      port("exported_video", "导出成片", "video"),
      port("delivery", "交付证据", "execution_ref"),
    ],
  ),
  node(
    "report",
    "Report",
    "成本、质量、provider lineage",
    "汇总质量、成本与人工决策证据。",
    [1000, 260, 170],
    [port("execution", "执行证据", "execution_ref", true)],
    [port("report", "汇总报告", "execution_ref")],
  ),
];

export const productionCanvasEdges: ProductionCanvasEdge[] = [
  edge("brief", "production_brief", "assets", "production_brief"),
  edge("brief", "production_brief", "script", "production_brief"),
  edge("assets", "selected_assets", "script", "selected_assets"),
  edge("script", "script", "timeline", "script"),
  edge("timeline", "timeline_clip", "storyboard", "timeline_clip"),
  edge(
    "storyboard",
    "approved_storyboard",
    "video",
    "approved_storyboard",
    "selected_output",
  ),
  edge("timeline", "timeline_clip", "placement", "timeline_clip"),
  edge(
    "video",
    "approved_video",
    "placement",
    "approved_video",
    "selected_output",
  ),
  edge("placement", "placed_timeline", "render", "timeline"),
  edge("render", "rendered_video", "export", "rendered_video"),
  edge("export", "delivery", "report", "execution"),
];
