#!/usr/bin/env python3
"""Compute harness quality scores from audit and run artifacts."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

if __package__ in {None, ""}:
    sys.path.append(str(Path(__file__).resolve().parents[2]))

from scripts.harness._common import ARTIFACTS_ROOT, read_json, write_json

REPO_ROOT = Path(__file__).resolve().parents[2]
AUDIT_ROOT = REPO_ROOT / "artifacts" / "repo_audit" / "latest"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run-id", help="Optional run id; defaults to the latest run directory")
    parser.add_argument(
        "--contract-report",
        type=Path,
        default=AUDIT_ROOT / "contracts-report.json",
    )
    parser.add_argument(
        "--output-json",
        type=Path,
        default=AUDIT_ROOT / "quality-score.json",
    )
    parser.add_argument(
        "--quality-score-path",
        type=Path,
        default=REPO_ROOT / "QUALITY_SCORE.md",
    )
    parser.add_argument(
        "--write-quality-score",
        action="store_true",
        help="Write QUALITY_SCORE.md as a generated snapshot",
    )
    return parser.parse_args()


def latest_run_dir() -> Path | None:
    candidates = sorted(ARTIFACTS_ROOT.glob("*/manifest.json"))
    return candidates[-1].parent if candidates else None


def clamp(value: float) -> float:
    return max(0.0, min(1.0, round(value, 2)))


def load_inputs(args: argparse.Namespace) -> tuple[dict[str, Any], Path | None]:
    report = read_json(args.contract_report, default={}) or {}
    run_dir = ARTIFACTS_ROOT / args.run_id if args.run_id else latest_run_dir()
    return report, run_dir


def score_harness_availability(doctor: dict[str, Any]) -> float:
    checks = [
        bool(doctor.get("env_file_exists")),
        bool(doctor.get("frontend_port")),
        bool(doctor.get("api_port")),
        bool(doctor.get("nginx_port")),
        bool((doctor.get("frontend_root") or {}).get("ok")),
        bool((doctor.get("api_health") or {}).get("ok")),
        bool((doctor.get("nginx_login") or {}).get("ok")),
    ]
    return clamp(sum(checks) / len(checks)) if checks else 0.0


def score_structural_compliance(report: dict[str, Any]) -> float:
    summary = report.get("summary") or {}
    scores = [
        1 - min(1, summary.get("oversized_files", 0) / 300),
        1 - min(1, summary.get("route_handler_violations", 0) / 20),
        1 - min(1, summary.get("direct_query_files", 0) / 100),
        1 - min(1, summary.get("legacy_reference_files", 0) / 50),
        1 - min(1, summary.get("docs_drift_errors", 0) / 5),
    ]
    return clamp(sum(scores) / len(scores)) if scores else 0.0


def score_browser_coverage(browser_flow: dict[str, Any], run_dir: Path | None) -> float:
    if not browser_flow:
        return 0.0
    artifact_checks = [
        bool((run_dir / "browser_flow.json").exists()) if run_dir else False,
        bool((run_dir / "console.json").exists()) if run_dir else False,
        bool((run_dir / "network.json").exists()) if run_dir else False,
        bool((run_dir / "dom_snapshot.json").exists()) if run_dir else False,
        bool((run_dir / "screenshot.png").exists()) if run_dir else False,
    ]
    artifact_score = sum(artifact_checks) / len(artifact_checks)
    engine = browser_flow.get("selected_engine")
    engine_score = 1.0 if engine == "chrome_devtools_mcp" else 0.5 if browser_flow.get("result_evidence", {}).get("ok") else 0.0
    status_score = 1.0 if browser_flow.get("selected_status") == "passed" else 0.5 if browser_flow.get("selected_status") == "degraded" else 0.0
    return clamp((artifact_score + engine_score + status_score) / 3)


def score_pipeline_reliability(summary: dict[str, Any], golden_path: dict[str, Any], trace_run: dict[str, Any]) -> float:
    checks = [
        summary.get("doctor_status") == "passed",
        summary.get("golden_path_status") == "passed",
        bool(golden_path.get("ok")),
        bool((trace_run.get("metrics") or {}).get("record_count", 0) >= 0),
    ]
    return clamp(sum(1 for item in checks if item) / len(checks)) if checks else 0.0


def render_quality_md(snapshot: dict[str, Any]) -> str:
    metrics = snapshot["scores"]
    summary = snapshot["contract_summary"]
    run_id = snapshot.get("run_id") or "none"
    return "\n".join(
        [
            "# Quality Score",
            "",
            "Generated by `scripts/harness/score_quality.py` from harness and contract artifacts.",
            "",
            "## Current Snapshot",
            "",
            f"- Harness Availability: {metrics['harness_availability']:.2f}",
            f"- Structural Compliance: {metrics['structural_compliance']:.2f}",
            f"- Browser Evidence Coverage: {metrics['browser_evidence_coverage']:.2f}",
            f"- Pipeline Reliability: {metrics['pipeline_reliability']:.2f}",
            "",
            f"Latest validated run: `{run_id}`",
            "",
            "## Contract Summary",
            "",
            f"- Oversized files: `{summary.get('oversized_files', 0)}`",
            f"- Route handler violations: `{summary.get('route_handler_violations', 0)}`",
            f"- Direct query files: `{summary.get('direct_query_files', 0)}`",
            f"- Legacy reference files: `{summary.get('legacy_reference_files', 0)}`",
            f"- Docs drift errors: `{summary.get('docs_drift_errors', 0)}`",
            "",
            "## Artifact Inputs",
            "",
            f"- Contract report: `{snapshot.get('contract_report_path')}`",
            f"- Browser flow artifact: `{snapshot.get('browser_flow_path')}`",
            f"- Golden path artifact: `{snapshot.get('golden_path_path')}`",
            f"- Trace artifact: `{snapshot.get('trace_run_path')}`",
        ]
    ) + "\n"


def main() -> int:
    args = parse_args()
    report, run_dir = load_inputs(args)
    summary = read_json(run_dir / "summary.json", default={}) if run_dir else {}
    doctor = read_json(run_dir / "doctor.json", default={}) if run_dir else {}
    browser_flow = read_json(run_dir / "browser_flow.json", default={}) if run_dir else {}
    golden_path = read_json(run_dir / "golden_path.json", default={}) if run_dir else {}
    trace_run = read_json(run_dir / "trace-run.json", default={}) if run_dir else {}

    snapshot = {
        "generated_at": summary.get("generated_at"),
        "run_id": run_dir.name if run_dir else None,
        "contract_report_path": str(args.contract_report),
        "browser_flow_path": str(run_dir / "browser_flow.json") if run_dir else None,
        "golden_path_path": str(run_dir / "golden_path.json") if run_dir else None,
        "trace_run_path": str(run_dir / "trace-run.json") if run_dir else None,
        "contract_summary": report.get("summary", {}),
        "scores": {
            "harness_availability": score_harness_availability(doctor or {}),
            "structural_compliance": score_structural_compliance(report or {}),
            "browser_evidence_coverage": score_browser_coverage(browser_flow or {}, run_dir),
            "pipeline_reliability": score_pipeline_reliability(summary or {}, golden_path or {}, trace_run or {}),
        },
    }

    write_json(args.output_json, snapshot)
    if args.write_quality_score:
        args.quality_score_path.write_text(render_quality_md(snapshot), encoding="utf-8")
    print(json.dumps(snapshot, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
