import type { Story, StoryNovelRevision } from "../src/utils/api/types";

export const story = {
  id: 1,
  business_id: "story-business-id",
  title: "红尘纪事",
  genre: "drama",
  workflow_mode: "novel_adaptation_v1",
  story_seed_status: "confirmed",
  story_seed: {
    schema: "story_seed_v2",
    outline_text: "褚蓝从红尘样本追查到暗渠入口。",
    title: "红尘纪事",
    premise: "一份异常样本揭开城市规则的裂缝。",
    protagonists: [],
    world_constraints: [],
    central_conflict: "真相与既有秩序冲突。",
    ending_direction: "褚蓝确认入口并继续追查。",
    content_constraints: [],
    structured_outline: {
      status: "confirmed",
      version: 7,
      thread_schedule_version: 1,
      thread_payoffs: [],
      chapters: [
        {
          position: 1,
          title: "第一章",
          goal: "发现线索",
          key_events: ["发现红尘"],
          character_focus: ["褚蓝"],
          open_threads: [],
          end_state: "保存样本",
        },
        {
          position: 2,
          title: "第二章",
          goal: "追查来源",
          key_events: ["检查暗渠"],
          character_focus: ["褚蓝"],
          open_threads: [],
          end_state: "锁定入口",
        },
      ],
    },
  },
  status: "draft",
  is_public: false,
  created_at: "2026-07-24T00:00:00Z",
  updated_at: "2026-07-24T00:00:00Z",
} as Story;

export const pendingRevision: StoryNovelRevision = {
  id: 26,
  business_id: "revision-business-id",
  story_business_id: story.business_id,
  task_id: 7001,
  style: "prose",
  target_words: 0,
  chapter_count: 2,
  total_words: 3500,
  revision_number: 3,
  lifecycle_status: "draft",
  continuity_status: "review_required",
  adaptation_plan_status: "empty",
  generation_plan: {
    schema: "story_novel_generation_plan.v2",
    version: 5,
    status: "ready",
    phase: "ready",
    chapter_count: 2,
    planned_min_chars: 6000,
    planned_target_chars: 8000,
    planned_max_chars: 10000,
    length_profile: {
      profile_id: "standard_serial",
      default_min_chars: 3000,
      default_target_chars: 4000,
      default_max_chars: 5000,
    },
    chapter_length_overrides: {},
    chapters: [
      {
        position: 1,
        title: "第一章",
        goal: "发现线索",
        target_chars: 4000,
        min_chars: 3000,
        max_chars: 5000,
        generation_status: "body_ready",
        extraction_status: "blocked",
      },
      {
        position: 2,
        title: "第二章",
        goal: "追查来源",
        target_chars: 4000,
        min_chars: 3000,
        max_chars: 5000,
        generation_status: "pending",
        extraction_status: "pending",
      },
    ],
  },
  continuity_ledger: {
    state_status: "generating",
    chapters: {
      "1": {
        status: "body_ready",
        generation_status: "body_ready",
        extraction_status: "blocked",
        char_count: 3500,
      },
    },
  },
  chapters: [
    {
      business_id: "chapter-1",
      position: 1,
      title: "第一章",
      content_text: "第一章正文",
      summary: "发现红尘",
      review_status: "ready",
      actual_chars: 3500,
      updated_at: "2026-07-24T00:00:00Z",
    },
  ],
  created_at: "2026-07-24T00:00:00Z",
  updated_at: "2026-07-24T00:00:00Z",
};

export const completedRevision: StoryNovelRevision = {
  ...pendingRevision,
  total_words: 7200,
  continuity_ledger: {
    state_status: "failed",
    stale_from_position: 2,
    recovery_from_position: 2,
    chapters: {
      "1": {
        status: "ready",
        generation_status: "ready",
        extraction_status: "ready",
        char_count: 3500,
        state_validation: { status: "passed", violations: [] },
      },
      "2": {
        status: "state_pending",
        generation_status: "state_pending",
        extraction_status: "blocked",
        char_count: 3700,
      },
    },
  },
  chapters: [
    {
      ...pendingRevision.chapters[0],
      generation_status: "ready",
      extraction_status: "ready",
    },
    {
      business_id: "chapter-2",
      position: 2,
      title: "第二章",
      content_text: "第二章正文",
      summary: "检查暗渠",
      review_status: "review_required",
      actual_chars: 3700,
      generation_status: "state_pending",
      extraction_status: "blocked",
      updated_at: "2026-07-24T00:03:00Z",
    },
  ],
};
